# Generated by Django 2.1.7 on 2019-02-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_character', models.CharField(max_length=100, null=True)),
                ('char_health', models.IntegerField(default=100)),
                ('selected_enemy', models.CharField(max_length=100, null=True)),
                ('enemyHealth', models.IntegerField(default=100)),
            ],
        ),
    ]
