# Generated by Django 2.1.7 on 2019-02-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_character', models.CharField(max_length=100, null=True)),
                ('char_health', models.IntegerField(default=100)),
                ('selected_enemy', models.CharField(max_length=100, null=True)),
                ('enemyHealth', models.IntegerField(default=100)),
                ('game_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
